### PR TITLE
feat: set app version as `dev` when building locally

### PR DESCRIPTION
**Pull request by setchy**
A small enhancement to help when doing local development remember which version of the app is running 😎 

Screenshot 2024-06-14 at 9 39 24 AM

### CODE REVIEW

**Review by bmulholland — APPROVED** [review]
Good idea. Could also consider changing a key color, like the sidebar background, so it's hard to miss

**Comment by afonsojramos** [comment]
Would also be nice to have "demo notifications" so that we don't need to load real ones 🤔

**Comment by setchy** [comment]
I have a `stash` locally that mocks the API response.  Could add that into the scope of #980

**Comment by setchy** [comment]
A while ago I was using https://github.com/setchy/gitify-notifications-sandbox too, which could be transferred into the `gitify-app` organization if we wanted "real" notifications

**Comment by afonsojramos** [comment]
I suppose there's the two cases, the ones where we just want to work with UI, and the cases where we need to work with the flow themselves.

**Pull request merged**
