### PR TITLE
feat: add conditional render on "Mark as Done" Btn

### PR DESCRIPTION
**Pull request by julienperrault**
Entreprise API doesn't provide "Mark as Done". So i have done this PR to remove "Mark as Done" Btns.
closes : https://github.com/gitify-app/gitify/issues/1412

### CODE REVIEW

**Review by setchy — CHANGES_REQUESTED** [review]
"Mark as Done" was added to GitHub Enterprise Server in version 3.13. See https://docs.github.com/en/enterprise-server@3.13/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done

Instead, we should look to make the API call resilient for users on GitHub Enterprise Servier 3.12 or older

**Comment by setchy** [comment]
@julienperrault - thoughts on https://github.com/gitify-app/gitify/pull/1424 👀

**Comment by akellbl4** [comment]
@setchy I like the solution with hiding, but it can be improved by checking the GHE version and not hiding for any GHE instance.

**Comment by akellbl4** [comment]
I haven't checked but if the app switches to https://github.com/octokit/octokit.js it might be easier to detect supported features

**Comment by setchy** [comment]
> @setchy I like the solution with hiding, but it can be improved by checking the GHE version and not hiding for any GHE instance.

agree :) - updated https://github.com/gitify-app/gitify/pull/1424 to use version information.  

If you are able to test the branch locally @akellbl4 @julienperrault that would be greatly appreciated 🙏

**Comment by setchy** [comment]
superseded by https://github.com/gitify-app/gitify/pull/1424

**Pull request closed without merging**
