### PR TITLE
chore: add `repo` scope to token login

### PR DESCRIPTION
**Pull request by afonsojramos**
Add `repo` scope to the token creation link to conform with the Login With An Access Token page.
image

The `repo` scope has been added in https://github.com/gitify-app/gitify/pull/538

### CODE REVIEW

**Comment by bmulholland** [comment]
What's this needed for?

**Comment by afonsojramos** [comment]
@bmulholland added the details to the description.

**Comment by bmulholland** [comment]
Sounds good! Looks like the change was clobbered, though?

**Comment by afonsojramos** [comment]
> Sounds good! Looks like the change was clobbered, though?

I suppose that users can still remove the `repo` token if they're not comfortable with giving it, but for the default behaviour I suppose that we should aim to get maximum compat.

**Comment by bmulholland** [comment]
I don’t think we’re talking about the same thing… I was saying that the diff is currently zero lines of code :)

**Comment by afonsojramos** [comment]
Must have gotten mangled by the merge, sorry about that!

**Review by bmulholland — APPROVED** [review]

**Pull request merged**
