### PR TITLE
refactor(icons): replace cog icon with octicons prime version

### PR DESCRIPTION
**Pull request by setchy**
**Before**
Screenshot 2024-03-14 at 7 40 11 AM

**After**
Screenshot 2024-03-11 at 3 03 23 PM

### CODE REVIEW

**Review by afonsojramos — CHANGES_REQUESTED** [review]
That icon feels soulless. I'd prefer to stay with the current one, at least with the current design of gitify.

**Comment by afonsojramos** [comment]
Or maybe I just need to get used to it... I'm going to leave it simmering 🥘

**Comment by setchy** [comment]
> Or maybe I just need to get used to it... I'm going to leave it simmering 🥘

Simmer away 😉.  I noticed that the octicons are much sharper.   

> But if we do it, we should join #873 #874 and #876 with this one. It doesn't make sense to have them in separate PRs imo

Personal preference perhaps... I'm very much in favor of small, independent, isolated PRs to assist with review speed and keep the line changed to the smallest releasable, particularly with refactoring PRs

**Comment by afonsojramos** [comment]
Right, but in this case you are introducing icons that don't play well with each other if not done on one go.

I feel like if we switch to these icons we also need to completely revamp our UI to properly mimick GitHub's UI. As is, I still think ours are perfectly fine. If we do do these UI changes, then I think the icon changes make total sense

**Comment by setchy** [comment]
In the interest of moving this forward, I've consolidated into a single PR https://github.com/gitify-app/gitify/pull/885

**Pull request closed without merging**
