### PR TITLE
feat: linked issue indicator

### PR DESCRIPTION
**Pull request by setchy**
Parse PR body to extract linked issues/prs and display a visual indicator with appropriate mouse-over text

Screenshot 2024-05-30 at 10 27 55 PM

### CODE REVIEW

**Comment by bmulholland** [comment]
Is this something you'd use? I wouldn't, so would just be visual noise for me

**Comment by setchy** [comment]
> Is this something you'd use? I wouldn't, so would just be visual noise for me

I'm on the fence too...  It's in the GitHub Web UI, but not their mobile apps (as best as I can tell)...

**Comment by bmulholland** [comment]
Copying the Github UI is a good argument for doing it, noise or not :)

**Comment by setchy** [comment]
Will update this to use a "pill" once #1169 is merged

**Comment by setchy** [comment]
Updated to use "pill" format as to be introduced via #1169 

Screenshot 2024-06-02 at 3 29 54 PM

**Review by afonsojramos — APPROVED** [review]
With the pill, this looks pretty cool, thanks @setchy!

**Pull request merged**
