### PR TITLE
feat(accounts): enhance auth account data structure

### PR DESCRIPTION
**Pull request by setchy**
- Introduce new accounts type that unlocks the possibility of authenticating one or more accounts at once, across any combination of support auth methods (personal access token or oauth app) and across any platforms (github cloud or github enterprise server)

- Update logic to support new account structures

- Implemented a legacy auth/account migration process to help seamlessly transition existing authenticated users.

_Note: there is a handful of follow-up PRs required in order to expand functionality beyond "at most one account of each auth method"_

### CODE REVIEW

**Comment by setchy** [comment]
OK - @brandonweiss @afonsojramos - I feel like this is ready.  

It largely focuses on the new account data structure and legacy account migration logic.

**Comment by setchy** [comment]
_👀 looking into the coverage drop_

**Comment by brandonweiss** [comment]
@setchy I think you might have tagged the wrong person 😬

**Comment by bmulholland** [comment]
Any chance there's more that could be pulled out? Not sure when I'll have time for an 800 line review :)

**Comment by setchy** [comment]
It's as lean as it'll get. 

It's not as scary as it may appear

**Comment by setchy** [comment]
@bmulholland - thinking more about this... I _could_ do the following PRs

1. new unused types
* contains the new Account types
* set sensible defaults
* leave unused

2. migration utility
* logic to migrate legacy accounts to the new account structure

3. switch all API calls to use the new account object from 1 above.

**Review by afonsojramos — APPROVED** [review]
Managed to find the time and it looks good to me code wise! Will test locally in the next few minutes!

**Comment by setchy** [comment]
Thanks @afonsojramos - anything explode haha

**Comment by afonsojramos** [comment]
@setchy When I opened I didn't have the live one open. And now if I try to open the live one it doesn't open either.
image
image

**Comment by afonsojramos** [comment]
If I open both, "live" one first, then local, the local one show the login screen.
image
While the live one stays on the white screen.

**Comment by setchy** [comment]
🥹

**Comment by setchy** [comment]
The stacktrace might be unrelated to this PR... similar error reported in https://github.com/gitify-app/gitify/issues/1166

**Comment by afonsojramos** [comment]
Looking good!

**Pull request merged**
