### PR TITLE
feat: hide scrollbar

### PR DESCRIPTION
**Pull request by setchy**
Hide scrollbar

**Before**
Screenshot 2024-03-21 at 9 55 56 AM

**After**
Screenshot 2024-03-21 at 9 56 12 AM

### CODE REVIEW

**Comment by bmulholland** [comment]
What's your thinking on making this change? Usability best practices are to keep native scrollbars, as they afford scrolling.

**Comment by setchy** [comment]
> What's your thinking on making this change? Usability best practices are to keep native scrollbars, as they afford scrolling.

It looks a bit cleaner without the scrollbar, and matches the mockups that are currently on https://www.gitify.io/ (PR pending to update for v5 screenshots).  Scrolling is still supported

**Comment by afonsojramos** [comment]
Wouldn't it be better to customize the styling instead?

**Comment by setchy** [comment]
> Wouldn't it be better to customize the styling instead?

we could take that route instead if that's preferable

**Comment by setchy** [comment]
i originally did this as part of some local changes to help automate the collection of screenshots for gitify-app/website :)

**Comment by bmulholland** [comment]
Might be different in a native app type experience, but FWIW I read this a couple days ago: https://old.reddit.com/r/webdev/comments/1bhhu7k/scrollbar_customization/kveazqm/

**Comment by setchy** [comment]
Thanks @bmulholland @afonsojramos - i'll close this for now. appreciate the feebdack from you both 🙇

**Pull request closed without merging**
