### PR TITLE
feat: check for updates

### PR DESCRIPTION
**Pull request by setchy**
Based on #1395 from @bquorning 

Draft PR to consider:
- Adding a context menu for checking for updates manually
- Adding a scheduled timer to check for updates automatically (not just on app start)
- Display somewhere in the UI a visual indicator when there is a new version available

### CODE REVIEW

**Comment by setchy** [comment]
**Latest version**
Screenshot 2024-07-22 at 10 30 23 AM

**Update available**
Screenshot 2024-07-22 at 10 31 19 AM

**Comment by afonsojramos** [comment]
Love the idea, but I think the implementation in the UI is a bit weird. The behaviour that I see in these menubar apps is usually an indicator in the icon of the menubar and I think it is less intrusive and more informative at the same time, what do you think?

Example: Ollama
image
image
image

**Comment by setchy** [comment]
> Love the idea, but I think the implementation in the UI is a bit weird. The behaviour that I see in these menubar apps is usually an indicator in the icon of the menubar and I think it is less intrusive and more informative at the same time, what do you think?
> 
> Example: Ollama
> image
> image
> image
> 

I like that approach. Would you be interested in helping pivot this way?

**Comment by setchy** [comment]
I also like the `restart to update` context menu entry. That seems better than doing it automatically

**Comment by setchy** [comment]
Another thought, maybe our menu system could adopt something like this

- check for update 
-- show status if update available 
-- show restart to update if available 
- separator
- Developer (sub menu)
-- Reload
-- Toggle Developer Tools
-- separator 
- Quit

**Comment by setchy** [comment]
@afonsojramos - pushed updates to this branch that add the extra context menu elements.

Not sure the best way to update the tray icon.  We'd either need to create a new png, or, manipulate the tray title (used for notification counts) to display a visual indicator

**Review by bmulholland — APPROVED** [review]
Really nice

**Pull request merged**
