### PR TITLE
feat: labels indicator

### PR DESCRIPTION
**Pull request by setchy**
Screenshot 2024-05-30 at 10 58 30 PM

### CODE REVIEW

**Comment by setchy** [comment]
Tests still WIP.

Would appreciate feedback on color and icon. Went with a purple tag for the time being

**Comment by bmulholland** [comment]
My take is that using color where it's not conveying information makes it harder to parse the places where color is important (like PR status). Matching the text color should be fine, right?

**Comment by setchy** [comment]
> My take is that using color where it's not conveying information makes it harder to parse the places where color is important (like PR status). Matching the text color should be fine, right?

appreciate the feedback. thanks @bmulholland.  I'll make that change.

I might also try and see what render the labels as `pills` using the label.color looks like (like the Android GitHub app does)

**Comment by setchy** [comment]
updated to use pill format as to-be introduced by #1169 

Screenshot 2024-06-02 at 3 49 53 PM

**Review by afonsojramos — CHANGES_REQUESTED** [review]
Was about to finish the merge, but had to do the dishes 😂 
I think you're still missing a couple of places where labels need to be defined as I still see a couple of these around.
image

**Comment by setchy** [comment]
> Was about to finish the merge, but had to do the dishes 😂 I think you're still missing a couple of places where labels need to be defined as I still see a couple of these around. image

Haha - sorry about that.  

Where are you seeing this?

**Comment by afonsojramos** [comment]
> Haha - sorry about that.
> 
> Where are you seeing this?

image
On these two under `useNotifications.test.ts`

**Review by afonsojramos — APPROVED** [review]
Looking clean now, thanks 🧽

**Pull request merged**
