### PR TITLE
build(release): remove gh_token env

### PR DESCRIPTION
**Pull request by setchy**
~use default auto provisioned GitHub actions token instead of my custom PAT~

remove gh_token env variable. should use `github_token`

### CODE REVIEW

**Review by afonsojramos — CHANGES_REQUESTED** [review]
The default default GitHub actions token, afaik doesn't need to be provided at all, so we can just delete it I think!

**Comment by setchy** [comment]
> The default default GitHub actions token, afaik doesn't need to be provided at all, so we can just delete it I think!

even better.  i was trying to recall when this got added.  i think it was during our notorization dark days haha

**Comment by setchy** [comment]
looking again, i think it's needed so that it's passed as process.env...

**Comment by setchy** [comment]
no dice - had to revert this for the 5.8.0 release... without specifying GITHUB_TOKEN or GH_TOKEN, electron-builder doesn't work.  using GITHUB_TOKEN doesn't have enough permissions to upload artifacts to the release notes.  Will continue using GH_TOKEN for now.  Ideally we'd create this within the gitify-app org

**Pull request merged**
