### PR TITLE
chore(deps): Upgrade to Jest 28

### PR DESCRIPTION
**Pull request by bmulholland**

### CODE REVIEW

**Comment by bmulholland** [comment]
Well those type errors are really annoying... will look

**Comment by afonsojramos** [comment]
This probably needs a rebase since I merged the Jest 27 one.

**Comment by bmulholland** [comment]
The typechecking errors are caused by interlocking dependencies which cause duplicate installation of types. Honestly probably easiest to upgrade some of the other things first, then come back to this.

**Comment by bmulholland** [comment]
Current dependencies on/for this PR:
* main
  * **PR #619** <a href="https://app.graphite.dev/github/pr/gitify-app/gitify/619" target="_blank">Graphite</a> 
    * **PR #612** <a href="https://app.graphite.dev/github/pr/gitify-app/gitify/612" target="_blank">Graphite</a> 
      * **PR #579** <a href="https://app.graphite.dev/github/pr/gitify-app/gitify/579" target="_blank">Graphite</a> 
        * **PR #616** <a href="https://app.graphite.dev/github/pr/gitify-app/gitify/616" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/gitify-app/gitify/616?utm_source=stack-comment).

**Pull request merged**
