### PR TITLE
build: move lint into separate workflow 

### PR DESCRIPTION
**Pull request by setchy**

### CODE REVIEW

**Review by afonsojramos — CHANGES_REQUESTED** [review]
Hmmm, why exactly?

**Comment by setchy** [comment]
> Hmmm, why exactly?

Explicit check feedback

**Comment by afonsojramos** [comment]
> > Hmmm, why exactly?
> 
> Explicit check feedback 

Isn't looking at the workflow failure reason not enough? 😅

**Comment by setchy** [comment]
> > > Hmmm, why exactly?
> > 
> > Explicit check feedback 
> 
> Isn't looking at the workflow failure reason not enough? 😅

I think it's more intuitive if it is a separate step, whether that's a separate workflow file (lint.yml) or the same (test.yml).

We have this clarity already in Build App and Release App and Validators 😎

**Review by afonsojramos — APPROVED** [review]
Why not :D

**Comment by bmulholland** [comment]
IMHO this is best practice :)

**Pull request merged**
