### PR TITLE
feat: implement `showNotificationsCountInTray` setting

### PR DESCRIPTION
**Pull request by adufr**
## Related issues

#750 

## Context

Introduce a new setting (disabled by default), that uses the `tray.setTitle()` API to show the notifications count next to the tray icon.

image

## Discussion

There are quite a lot of changes because I had to pass `settings` into a few methods so that the `updateTrayIcon()` method could inherit them, as it now requires them.

It's also quite the mess in the `ipcMain.on('update-icon')` event handler, as I had to make sure the icon was refreshed whenever you enable/disable the setting, without losing the notifications count, which is not passed to the function it's not in the scope. (That's why props of `updateTrayIcon()` are optional)

If you have suggestions to make the implementation easier, please let me know.

I tried implementing some tests, I wanted to use the `tray.getTitle()` method to add more, but it looks like there's nowhere I could access the `tray` in the tests...

### CODE REVIEW

**Comment by setchy** [comment]
I'll take a look during the week @adufr - we have been quite preoccupied with getting v5 out.

**Comment by adufr** [comment]
> I'll take a look during the week @adufr - we have been quite preoccupied with getting v5 out.

Yeah I can imagine, congrats on that! You've done quite some work on that and the app looks much better now! 😁

**Comment by setchy** [comment]
On initial glance, it seems like a lot of unrelated files have changes. Is there a simpler path here?

**Comment by adufr** [comment]
@setchy I agree, but I didn't find any other way to make it work 😕

**Comment by adufr** [comment]
I fixed all conflicts following 5.1.0 release

**Comment by setchy** [comment]
Thanks @adufr - will take a look once #941 is merged

**Comment by adufr** [comment]
Do not hesitate to ping me once it's merged, I can probably rewrite the feature

**Comment by setchy** [comment]
@adufr - with #941 merged, I had an attempt at this feature over in https://github.com/gitify-app/gitify/pull/945 (didn't want to disrupt your branch).

Functionally, it seems to match.  Appreciate you taking a look

**Comment by adufr** [comment]
superseded by https://github.com/gitify-app/gitify/pull/945

**Pull request closed without merging**
