### PR TITLE
style: toggle on row click & action buttons order

### PR DESCRIPTION
**Pull request by afonsojramos**
Adds the functionality that was referred to in https://github.com/gitify-app/gitify/pull/1245#issuecomment-2171428582

Also sorted the order of the buttons to try to attain some added consistency.

image

### CODE REVIEW

**Comment by afonsojramos** [comment]
@setchy what do you think of this one?

**Review by setchy — APPROVED** [review]

**Comment by setchy** [comment]
> @setchy what do you think of this one?

clever ordering hack.  does mean we diverge a bit from GitHub UI, but worth it imo

**Comment by afonsojramos** [comment]
How so? Because here the disable notification is right next to the check? Don't think that's deviating too much tbh
image

**Comment by setchy** [comment]
> How so? Because here the disable notification is right next to the check? Don't think that's deviating too much tbh
> image
> 

Just recalling a previous PR discussion on these actions buttons. 

I'm good with it

**Pull request merged**
