### PR TITLE
feat(sidebar): highlight selected route

### PR DESCRIPTION
**Pull request by setchy**
Highlight sidebar button when route being shown

### CODE REVIEW

**Comment by bmulholland** [comment]
I expected to love it, but found the video confusing. I think it's because only two icons change color? Also, something about the red throws me off, like it's an error state.

That could just be because I'm not the one controlling it, though. So may or may not be valid feedback :)

**Review by bmulholland — APPROVED** [review]
Code looks good :)

**Comment by setchy** [comment]
> I expected to love it, but found the video confusing. I think it's because only two icons change color? Also, something about the red throws me off, like it's an error state.
> 
> That could just be because I'm not the one controlling it, though. So may or may not be valid feedback :)

It's meant to be orange, but agree it does come across differently.  Is there a different color you think would work well?

**Comment by afonsojramos** [comment]
Maybe no color, but a little triangle next to it? Let me draw something up!

**Comment by afonsojramos** [comment]
Like this? 
image

Otherwise, I'd just stick with the color on hover.

**Comment by setchy** [comment]
Or using a dot (ignore formatting/alignment for now) with matching icon color

Screenshot 2024-07-08 at 11 10 32 AM
Screenshot 2024-07-08 at 11 10 37 AM

**Comment by afonsojramos** [comment]
image
This is too packed. I say let's go with the hover's opacity, simpler implementation and cleaner UI

**Comment by bmulholland** [comment]
Yeah I agree that moving the icon would be weird.

**Comment by setchy** [comment]
agree, didn't intend for the icons to move around in the final version, hence the `(ignore formatting/alignment for now)` comment.

Nonetheless, will look to update the hover opacity instead

**Comment by setchy** [comment]
Me again 😅 

How about a simple tailwind ring?

Screenshot 2024-07-09 at 9 24 27 AM
Screenshot 2024-07-09 at 9 24 34 AM

**Comment by bmulholland** [comment]
I like the ring. Personal opinion though.

**Comment by setchy** [comment]
Updated to use a shadow. imho, this is the best of the options explored above. 


https://github.com/user-attachments/assets/a443b79d-30e6-42b5-94a5-e6862a95ce8b

**Comment by setchy** [comment]
Moving back to draft as @afonsojramos is looking into some things on his side

**Comment by setchy** [comment]
Closing this concept for now - I'll raise a separate PR just for updating the accounts route

**Pull request closed without merging**
