### PR TITLE
feat: launch minimized

### PR DESCRIPTION
**Pull request by setchy**
reopening this PR, since it may help with https://github.com/gitify-app/gitify/issues/1162

### CODE REVIEW

**Comment by setchy** [comment]
@camille-avatarmedical - are you able to test this branch please 🙏

**Review by bmulholland — APPROVED** [review]

**Comment by camille-avatarmedical** [comment]
@setchy : Sorry for the late reply. Can you provide a build and I will report it here if it works.

**Comment by setchy** [comment]
@camille-avatarmedical - could you kindly test on v5.8.0 🙏

**Comment by camille-avatarmedical** [comment]
I just updated on 5.8.1. The bug is still here. Gitify doesn't start minimized which is a bit strange, as if I understand correctly, it should. Am I missing something?

**Comment by setchy** [comment]
Sorry to hear that @camille-avatarmedical - i've re-opened your issue ticket and added a `help-wanted` label.

**Pull request merged**
