### PR TITLE
feat: using custom scrollbar css for dark mode

### LINKED ISSUE #1244: Custom Scrollbar
### 📝 Provide a description of the new feature

The default scrollbar on Windows is very ugly when using a dark theme
image

would be nice to have a custom scrollbar that conforms to the theme

### ➕ Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Araxeus**
Closes #1244 

Colors could be lighter, and im not sure if raw css is your preferred way of dealing with this, thoughts?

> used the colors from 
> https://github.com/gitify-app/gitify/blob/db9733c58211e8946894af2c41f6a0d6856b674d/tailwind.config.js#L12-L15

### CODE REVIEW

**Comment by setchy** [comment]
thanks @Araxeus 👏 

> Colors could be lighter, and im not sure if raw css is your preferred way of dealing with this, thoughts?

What about adding it into `index.html` directly?

**Comment by Araxeus** [comment]
<details><summary>Light mode: (didnt touch the style, thats how it natively looks on Windows 10)</summary>
<p>

image
image
image

</p>
</details> 

<details><summary>Dark mode:</summary>
<p>

image
image
image

</p>
</details>

**Comment by setchy** [comment]
Looks really nice!

Do you think it's worth making the `light` theme match the custom scrollbar (with suitable colors)?

**Comment by Araxeus** [comment]
> Do you think it's worth making the `light` theme match the custom scrollbar (with suitable colors)?

<details><summary>Here are some screenshots of that</summary>
<p>

image
image
image

</p>
</details> 

overall i'd say it looks better than the native one? should i commit this?

**Comment by Araxeus** [comment]
Well I can't even commit, it looks like its because the change is only affecting an html file, and biome throw an error

image

**Comment by setchy** [comment]
> Well I can't even commit, it looks like its because the change is only affecting an html file, and biome throw an error because it has nothing to check?

just pushed a fix to our `lint-staged` config.  can you try again now please

**Comment by Araxeus** [comment]
note: `html::-webkit-scrollbar` is used because a top level `::-webkit-scrollbar` would override the `html.dark::-webkit-scrollbar` style even with `!important`

which is a bit sad because it makes the css longer but I don't see a better way to do it

> sorry for the double force pushes but i made a typo twice in the commit description  🤦‍♂️

**Review by setchy — APPROVED** [review]
Looks really good to me. Keen to hear what the others think before merging

**Review by afonsojramos — APPROVED** [review]
Looks awesome to me! Always prefer custom scrollbars 😁

**Comment by setchy** [comment]
Just sharing an observation... scrollbars are now permanently visible on macOS when there is overflow content.

Previously they would hide/show based on scrolling activity.  

Screenshot 2024-06-17 at 7 41 43 AM
Screenshot 2024-06-17 at 7 40 26 AM

**Pull request merged**
