### PR TITLE
fix: open GitHub notifications page when clicking on GitHub icon

### LINKED ISSUE #543: The G logo should go to the configured git host home page
Currently there are 2 buttons which point to this repo: The G logo, and the GitHub logo at the bottom of the sidebar. The logo should open the home page of the configured git host instead.

### PR DESCRIPTION
**Pull request by hughlilly**
Changes the function that is called when the GitHub icon is clicked. Since the Gitify “G” icon already goes to the Gitify repo, this button was, in effect, a duplicate. It makes sense to provide a way to easily open the GitHub notifications page when there are no new notifications.

Closes #543.

### CODE REVIEW

**Review by JakeSidSmith — APPROVED** [review]
LGTM

**Comment by afonsojramos** [comment]
This doesn't fully make sense. I agree that the link should no longer go to `gitify`'s repo, but is going to notifications logical? If you have notifications you already have the bell icon...

**Review by afonsojramos — APPROVED** [review]

**Comment by afonsojramos** [comment]
If you're up for it, there are some tests to fix. Otherwise, I'll fix them myself ;)

**Comment by hughlilly** [comment]
> This doesn't fully make sense. I agree that the link should no longer go to `gitify`'s repo, but is going to notifications logical? If you have notifications you already have the bell icon... It is still an improvement however!

Oh I didn’t realise the bell icon went to notifications! I’d argue if there are no notifications it’s still useful to have the bell icon there, but grey, perhaps?

**Comment by afonsojramos** [comment]
Sounds good! Then I believe we can completely remove the GitHub icon. I see no need for it and see no other usage that would remove the duplication.

**Comment by afonsojramos** [comment]
Closing this PR in favour of #587.

**Pull request closed without merging**
