### PR TITLE
refactor: split settings into smaller components

### PR DESCRIPTION
**Pull request by setchy**
Split our growing `Settings` component into smaller, more focused components.

- Appearance Settings
- Notification Settings
- System Settings
- Settings Footer

### CODE REVIEW

**Review by bmulholland — APPROVED** [review]
It's a nice cleanup, thank you!

I do wonder if these per-component test files are more effort than they're worth. Integration-level tests could cover all of these, pretty much, without needing to have a test-per. As it is, I feel that the tests make the system harder to change without contributing much resiliency to errors.

**Comment by setchy** [comment]
> I do wonder if these per-component test files are more effort than they're worth. Integration-level tests could cover all of these, pretty much, without needing to have a test-per. As it is, I feel that the tests make the system harder to change without contributing much resiliency to errors.

I would argue the opposite. They're easy to write and easy to make changes. I haven't had any concerns

**Comment by bmulholland** [comment]
Oh cool, good news!

**Comment by afonsojramos** [comment]
It would have been way easier to merge this after #1318 :(

**Comment by afonsojramos** [comment]
Nevermind, it was rather easy afterall 😁

**Pull request merged**
