### PR TITLE
feat(refresh): reset interval and disable manual refresh

### PR DESCRIPTION
**Pull request by setchy**
This PR further helps reduce the chance of rate-limiting conditions by
- resetting the automated refresh timer upon a manual refresh (default: 1 minute) to prevent manual+auto fetching being close together
- disabling the manual refresh button, if clicked, until the next internal (default: 1 minute) to prevent repeated clicks

I have also taken the opportunity to refactor the hardcoded fetch interval into our Constants file

### CODE REVIEW

**Comment by adufr** [comment]
However, having a configurable interval could probably also help with the rate-limiting issue?
This way user would have more control over this issue, and if they report problems we could just instruct them to increase their refresh interval

**Comment by setchy** [comment]
> Just sharing my opinion about this: first point looks good to me but I don't agree with the second, IMO the user should be free to refresh whenever he wants, and if he gets rate-limited because he clicked the refresh button too many times, too bad for him but that's his problem I often use this button and this change would badly affect my experience 🙁

You have a need to refresh multiple times within the minute? 🤔

**Comment by setchy** [comment]
> However, having a configurable interval could probably also help with the rate-limiting issue?

Raised this as a new FR #1027 1027

**Comment by setchy** [comment]
Kind of weird... `pnpm test -- --coverage --verbose` works locally, but `pnpm test -- --coverage --runInBand --verbose` isn't... 🤔

**Comment by afonsojramos** [comment]
Agree with @adufr here. Refreshing manually may increase usage, but it was manual, so that's the user's responsibility. We should not take that "power" away imo.

**Comment by setchy** [comment]
> Agree with @adufr here. Refreshing manually may increase usage, but it was manual, so that's the user's responsibility. We should not take that "power" away imo.

OK then....

**Comment by afonsojramos** [comment]
Reverting the change in https://github.com/gitify-app/gitify/pull/1014/commits/e62aa37d0014cea3c1061ee9cb3eff0fa0218589, we can iterate in the future if needed. Let's get `5.3.0` out!

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
