### PR TITLE
chore(deps): Remove history dependency

### PR DESCRIPTION
**Pull request by bmulholland**
This was supposed to be removed as part of the react-router v6 upgrade (which moves history to a direct dependency), but it was clobbered by renovate

### CODE REVIEW

**Comment by bmulholland** [comment]
Current dependencies on/for this PR:
* main
  * **PR #648** <a href="https://app.graphite.dev/github/pr/gitify-app/gitify/648" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/gitify-app/gitify/648?utm_source=stack-comment).

**Comment by bmulholland** [comment]
Ah I guess the tests have that dependency still... WDYT @afonsojramos, should we swap the tests and remove the direct dependency? Or keep the dev dependency and just upgrade the package?

**Comment by afonsojramos** [comment]
> Ah I guess the tests have that dependency still... WDYT @afonsojramos, should we swap the tests and remove the direct dependency? Or keep the dev dependency and just upgrade the package?

If there is an alternative to it, I think that we can/should remove it!

**Comment by bmulholland** [comment]
Wow, nice work. It's less code, too!

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
